spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update